# Generated by Django 5.2.3 on 2025-06-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='catagory',
            new_name='category',
        ),
    ]
